spring.datasource.driver-class-name=org.postgresql.Driver
# データベース名
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres     
# ユーザー名
spring.datasource.username=postgres     
# パスワード
spring.datasource.password=postgres 