spring.application.name=SamplePractice
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/SamplePractice
spring.datasource.username=postgres
spring.datasource.password=postgres

# Mybatis接続設定
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity

# SQLログ出力（デバッグ用）
logging.level.com.example.demo.dao=DEBUG

# Thymeleaf設定
spring.thymeleaf.cache=false

# サーバーポート
server.port=8080