#spring.application.name=spring_user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/User-db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Mybatis接続設定
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.demo.entity
#キャメルケース変換する設定（user_name → userName）
mybatis.configuration.map-underscore-to-camel-case=true